name: Build HyenaCurrency Plugin

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Kotlin
        uses: fwcd/setup-kotlin@v1

      - name: Build with Maven
        run: mvn clean package

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: HyenaCurrency
          path: target/HyenaCurrency-*.jar
